backup:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    #password: Tcsz2022***
    dbName: xicheng_assessment
    backupPath: C:/backup
spring:
  application:
    name: westAssessment
  datasource:
    # 采用动态选取
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        # 主数据库
        master:
          url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: 123456
          #password: Tcsz2022***
          driver-class-name: com.mysql.cj.jdbc.Driver
        # 副数据库
        xicheng_assessment:
          url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconect=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: 123456
          #password: Tcsz2022***
          driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  #  config: classpath:logback.xml
  level:
    root: info
    com.tc.assessment: debug

